# Generated by Django 4.2.6 on 2023-11-02 18:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdConditions',
            fields=[
                ('shipment_id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('temperature_upper_limit', models.FloatField()),
                ('temperature_lower_limit', models.FloatField()),
                ('humidity_upper_limit', models.FloatField()),
                ('humidity_lower_limit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.thresholdconditions')),
            ],
        ),
    ]
